### PR TITLE
Added S3 publishing to cwr-bundle, cwr-charm-pr and cwr-charm-release…

### PR DESCRIPTION
**Pull request by seman**
Added S3 publishing to `cwr-bundle`, `cwr-charm-pr` and `cwr-charm-release` actions. Also, updated the `bundlebuilder.py` command-line interface code.

### CODE REVIEW

**Comment by kwmonroe** [comment]
Yuuuuuuuck.  The sheer duplication in `actions.yaml` makes my eyes twitch.  I understood the need to merge #118 to fix stuff that was already released, but I thought we were gonna go for an action to push cwr results off the box -- #99.

Once this stuff lands, it's gonna be tough to get out.  Would you please consider waiting for a +2 before merging?  I don't think all the dev/maint stakeholders have thought this through.

**Comment by ktsakalozos** [comment]
This PR seems to go against what is discussed here: https://github.com/juju-solutions/layer-cwr/pull/122

**Comment by ktsakalozos** [comment]
Also note that we might need to revert https://github.com/juju-solutions/layer-cwr/pull/110 should we dicide to implement https://github.com/juju-solutions/layer-cwr/pull/122

**Comment by johnsca** [comment]
Per Torsten, we're going to move forward with this and refactor later to model storage properly in the Juju model.

**Pull request merged**
