### PR TITLE
rename build-* to cwr-*

### PR DESCRIPTION
**Pull request by kwmonroe**
Our action naming has rubbed me wrong for a while.  While it's true that `build-on-foo` does indeed build a charm, the larger intention is to run *cwr* on a charm when *foo* happens.  To that end, I propose the following renames before we get so widespread that a rename becomes impractical:

* `build-on-commit` -> `cwr-charm-commit`
  * Rationale:  Run CWR when charm source has a new commit.
* `build-on-release` -> `cwr-charm-release`
  * Rationale:  Run CWR when charm source has been tagged in github with a [release tag](https://help.github.com/articles/creating-releases/).
* `build-bundle` -> `cwr-bundle`
  * Rationale:  Run CWR when bundle contents change.

In addition to these changes, I've renamed `lp-id` action params to `namespace`, because that matches the ecosystem nomenclature better imo.

This PR also helps address https://github.com/juju-solutions/bundle-cwr-ci/issues/12, where @mbruzek requested a prefix on cwr jobs to help distinguish them from other jobs on the jenkins host.  The spirit of his issue also includes renaming jobs like `RegisterController` and `RunCWR`, so this doesn't totally resolve his issue.  Still, grouping `cwr`-related jobs seems smart, so I've done that with the generated job names in this PR.

Make no mistake, this is a disruptive change that affects anyone that has become accustomed to our action names.  I think it's best we get it right and get it consistent sooner rather than later.  I'm open to suggestions if anyone disagrees with this proposal.

This is currently available in [cwr-58](https://jujucharms.com/u/juju-solutions/cwr/58) on `jdin:8080`, model `cwr-58`.  Tests with charm and bundle actions look clean:

http://juju.does-it.net:8080/

### CODE REVIEW

**Comment by johnsca** [comment]
I am +1 on these changes.

**Comment by petevg** [comment]
I am also +1 on the changes.

**Comment by ktsakalozos** [comment]
I would prefer something other than cwr because of two reasons:
1. CWR is a tool we are using. It might get deprecated next year, who knows... then again we named the charm cwr :)
2. CWR are initials that might not mean a lot to the user.

However, it seems I am a minority. So, lets merge this :)

**Comment by mbruzek** [comment]
https://github.com/juju-solutions/bundle-cwr-ci/issues/12 only asked for the Jenkins **jobs** to be prefixed with something so an alphanumeric listing on Jenkins would group the jobs together instead of intermingled with other jobs that might already be on the system. @kwmonroe You don't need to change the **action names** to reflect that if that would cause users confusion. 

I agree with @ktsakalozos that "cwr" may not be the best acronym to use in case someone wants to rename the tool in the future. Keeping the action names as they were would be fine and only changing the job name would be what I recommend.

**Comment by kwmonroe** [comment]
@ktsakalozos @mbruzek: Thanks for the feedback.  I feel pretty good about sticking with `cwr` as a prefix because all of these actions eventually call out to `run_cwr_in_container`.

If we support *foo* as a test mechanism next year, we can make `foo-*` actions that call out to `run_foo_in_container`.

Also consider the possibility of `cwr` flavors.  Perhaps in the future we have `cwr-lite` that only runs a subset of the tests.  Maybe your workflow then becomes "run cwr-lite on commit; run the full cwr on release".

Finally, I'm not too concerned with the tool being renamed -- as @ktsakalozos pointed out, we already named the charm `cwr`, so if we change names, there will be a new charm with the potential for new action names at that time.

**Pull request merged**
